### ISSUE TITLE
AttributeError: 'module' object has no attribute 'random'

### ISSUE THREAD

**Issue by harsham05** [lambdal/lambda-deep-learning-demo#1]
**I am following the Object Detection Tutorial, trying to Train SSD from scratch on MSCOCO**

```
python demo/object_detection.py \
--mode=train --model_dir=~/demo/model/ssd300_mscoco \
--network=ssd300 --augmenter=ssd_augmenter --batch_size_per_gpu=16 --epochs=100 \
--dataset_dir=/mnt/data/data/mscoco --num_classes=81 --resolution=300 \
--feature_net=vgg_16_reduced --feature_net_path=demo/model/VGG_16_reduce/VGG_16_reduce.p \
train_args --learning_rate=0.001 --optimizer=momentum --piecewise_boundaries=60,80 \
--piecewise_lr_decay=1.0,0.1,0.01 --dataset_meta=train2014,valminusminival2014 \
--callbacks=train_basic,train_loss,train_speed,train_summary \
--skip_l2_loss_vars=l2_norm_scaler --summary_names=loss,learning_rate,class_losses,bboxes_losses
```

Which version of Tensorflow do I need to use for this tutorial? I tried both 1.0.0 & 1.11.0 in Python2.7 virtual environments.

*>>> tensorflow.__version__
'1.11.0'* 

```
loading annotations into memory...
Done (t=9.26s)
creating index...
index created!
loading annotations into memory...
Done (t=7.51s)
creating index...
index created!
Traceback (most recent call last):
  File "demo/object_detection.py", line 134, in <module>
    main()
  File "demo/object_detection.py", line 130, in main
    runner.run()
  File "./source/runner/runner.py", line 146, in run
    self.create_graph()
  File "./source/runner/parameter_server_runner.py", line 132, in create_graph
    reduced_ops = self.replicate_graph()
  File "./source/runner/parameter_server_runner.py", line 73, in replicate_graph
    batch = self.inputter.input_fn()
  File "./source/inputter/object_detection_mscoco_inputter.py", line 231, in input_fn
    num_parallel_calls=12)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1007, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2248, in __init__
    super(ParallelMapDataset, self).__init__(input_dataset, map_func)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2216, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1473, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 865, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1411, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "./source/inputter/object_detection_mscoco_inputter.py", line 230, in <lambda>
    image_id, file_name, classes, boxes),
  File "./source/inputter/object_detection_mscoco_inputter.py", line 208, in parse_fn
    speed_mode=False)
  File "./source/augmenter/ssd_augmenter.py", line 532, in augment
    speed_mode=speed_mode)
  File "./source/augmenter/ssd_augmenter.py", line 418, in preprocess_for_train
    image, boxes = random_zoom_out(image, boxes)
  File "./source/augmenter/ssd_augmenter.py", line 283, in random_zoom_out
    uniform_random = tf.random.uniform([], 0, 1.0, seed=seed)
AttributeError: 'module' object has no attribute 'random'
```

**Comment by chuanli11** [comment]
Hi, I am using 1.12.

**Comment by harsham05** [comment]
Thanks @chuanli11 what are your thoughts on the Traceback?

**Comment by ideallyworld** [comment]
I am using 1.10. I also meet the seem problem when running the test_generation.py (tensorflow demo). Have you solve it?

**Comment by ideallyworld** [comment]
I am using 1.10. I also meet the seem problem when running the test_generation.py (tensorflow demo). Have you solve it?
